[package]
name = "grafbase-client-generator"
version = "0.1.0"
edition = "2021"
description = "The Grafbase TypeScript client generator"
license = "Apache-2.0"
homepage = "https://grafbase.com"
keywords = ["grafbase", "typescript", "graphql"]
readme = "README.md"
repository = "https://github.com/grafbase/grafbase"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
expect-test = "1.4.1"
indoc = "2.0.1"
dprint-plugin-typescript = "0.85.0"

[dependencies]
